### ISSUE TITLE
Request: Session Events to be a non-modal dialog window

### ISSUE THREAD

**Issue by samkatakouzinosracing** [stintanalyzer/stintanalyzer#6]
I'm interested in using the Session Events window feature. 
At the moment the window is modal. 
I think making it non-modal would help me move the main app window on my single monitor setup. 
Currently once the Session Events window is up I can't move nor minimize the main app window out the way to see iRacing.

**Comment by stintanalyzer** [comment]
Sorry, just now seeing this, I will try to put this in the next release.  Although it might still be a few weeks.

**Comment by stintanalyzer** [comment]
This has been changed.
