### ISSUE TITLE
Unhandled Exception Error - Persistent Despite Following FAQ Guidance

### ISSUE THREAD

**Issue by gitterpr** [stintanalyzer/stintanalyzer#9]
Hello,

I've followed the video in FAQ about how to correct the Unhandled Exception Error by deleting the Crixus/user folder for the correct file. However, I delete the file and reinstall SA but still continue to receive the correct user file error upon re-installation. Any help is appreciated.

Thanks,

**Comment by thomprl** [comment]
Resolved the issue by deleting the StintAnalyzer.saconfig file in Documents/StintAnalyzer.
